In [1]:
#Numpy 

In [3]:
#create a array using numpy 

#create a 1-D array 

import numpy as np 

arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [6]:
arr2=np.array([1,2,3,4,5,6])

arr2=arr2.reshape(2,3)

print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
#Different ways to create nd array 



In [8]:
arr3=np.arange(1,10,1)
print(arr3)

[1 2 3 4 5 6 7 8 9]


In [9]:
arr4=np.arange(1,10,2)
print(arr4)

[1 3 5 7 9]


In [12]:
np.arange(0,12,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [13]:
#array filled with only 1 

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#Identity matrix

np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [21]:
#linspace 

arr5=np.linspace(0,10,20).reshape(4,5)
print(arr5)

[[ 0.          0.52631579  1.05263158  1.57894737  2.10526316]
 [ 2.63157895  3.15789474  3.68421053  4.21052632  4.73684211]
 [ 5.26315789  5.78947368  6.31578947  6.84210526  7.36842105]
 [ 7.89473684  8.42105263  8.94736842  9.47368421 10.        ]]


In [22]:
#Attributes of numpy array 

arr=np.arange(1,6,1)
print("Array\n : ",arr)
print("Array Shape \n : ",arr.shape)
print("Size : number of elements : \n " ,arr.size)
print("Data Type \n",arr.dtype)
print("Item size in byte \n : " , arr.itemsize)

Array
 :  [1 2 3 4 5]
Array Shape 
 :  (5,)
Size : number of elements : 
  5
Data Type 
 int64
Item size in byte 
 :  8


In [24]:
#creating a random array 

np.random.rand(2)

array([0.47370142, 0.45361511])

In [26]:
np.random.randint(1,10,(3,4))

array([[4, 7, 9, 3],
       [2, 2, 3, 5],
       [3, 4, 9, 9]], dtype=int32)

In [27]:
#Array attributes and method 

normal_array = np.arange(25)
ranarr= np.random.randint(0,50,10)

print(normal_array)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 6 13 27 39 26 18 47 34 29 13]


In [28]:
ranarr.min()

np.int32(6)

In [31]:
print(ranarr.max())

47


In [33]:
print(ranarr.argmax()) # Returns the index of the maximum element in an array 

6


In [34]:
print(ranarr.argmin())

0


In [35]:
#Bracket indexing and selection 

normal_array[3]

np.int64(3)

In [36]:
#selecting a range of values 

normal_array[1:3]

array([1, 2])

In [37]:
#Broadcasting of numpy array 

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])


arr1+arr2

array([5, 7, 9])

In [38]:
arr3=np.array([11,12,13])
arr3+10

array([21, 22, 23])

In [39]:
#Broadcasting with 2D Array 

arr2d=np.arange(0,6).reshape(2,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
arr2d+[10,20,20]

array([[10, 21, 22],
       [13, 24, 25]])

In [41]:
#column broadcasting 

arr2d+[[10],[20]]

array([[10, 11, 12],
       [23, 24, 25]])

In [42]:
#Numpy vectorized operation 

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element wise addition 

print("Addition : ",arr1+arr2)
print("Subtraction : ",arr1-arr2)
print("Multiplication : ",arr1*arr2)

Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]


In [43]:
#Universal function 

arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [44]:
#Exponenetial 
print(np.exp(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [45]:
#Sine
print(np.sin(arr))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [46]:
#natural log 
print(np.log(arr))

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [47]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
#Slicing array 

print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [49]:
print(arr[1:,1:])

[[ 6  7  8]
 [10 11 12]]


In [50]:
#Modify array elements 

arr[0,0]=100

In [51]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [52]:
#calculating statistical data 

data = np.array([1,2,3,4,5])
mean = np.mean(data)
stv=np.std(data)


#Normalized data 

normalizeddata=(data-mean)/stv
print("Normalized Data : ",normalizeddata)

Normalized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [54]:
#Logical Operation 

data[(data<5)]

array([1, 2, 3, 4])